#!/bin/sh

config="$(ppq_parse < package.ppq)"
name="$(echo "$config" | grep '^set=#package#name=' | cut -d'=' -f3)"
bin="$(echo "$config" | grep '^set=#package#bin=' | cut -d'=' -f3)"

ppq_build --target "${name}-bin" && build/"$bin"
