#!/bin/sh

q="dependencies"

while [ $# -ne 0 ]
do
  case "$1" in
    --test) q="test_dependencies";;
  esac
  shift
done

ppq_parse < package.ppq | grep '^append=#'"$q"'=' | cut -d'=' -f3 | sed 's/^#'"$q"'#//'
