#!/bin/sh

mkdir -p cplusplus_modules

ppq_path="$(cd "$(dirname -- "$(command -v -- "$0")")" && pwd -P)/$(basename -- "$(command -v -- "$0")")"

ppq_parse < package.ppq | sed 's/=#test_dependencies=/=#dependencies=/g;s/=#test_dependencies#/=#dependencies#/' | awk -v ppq="$ppq_path" '
BEGIN {
  FS="="
  ndep=0
}

$1=="set" && $2 ~ /#dependencies#.*/ {
  field[$2]=$3;
  next
}

$1=="append" && $2=="#dependencies" {
  deps[ndep++]=$3;
  next
}

END {
  for(dep in deps) {
    d = deps[dep];
    name = d;
    sub(/^#dependencies#/, "", name);
    user = field[d "#location#ref"];
    sub(/\/.+$/, "", user);
    cmd = "mkdir -p cplusplus_modules/" user;
    print cmd;
    system(cmd);
    cmd = "git -C cplusplus_modules/" user " clone https://github.com/" field[d "#location#ref"] ".git";
    print cmd;
    system(cmd);
    if((d "#location#pin") in field) {
      cmd = "sh -c \"cd cplusplus_modules/" field[d "#location#ref"] " && git checkout " field[d "#location#pin"] "\"";
      print cmd;
      system(cmd);
    }
    cmd = "sh -c \"cd cplusplus_modules/" field[d "#location#ref"] " && " ppq " install\""
    print cmd;
    system(cmd);
  }
}
'
