#!/bin/sh

name="$(ppq_parse < package.ppq | grep '^set=#package#name=' | cut -d'=' -f3)"

echo "set(${name}_unit_tests_count 0)"
echo ""
echo "function(add_unit_test source_file)"
echo "  math(EXPR tmp \"\${${name}_unit_tests_count} + 1\")"
echo "  set(${name}_unit_tests_count \${tmp} PARENT_SCOPE)"
echo "  set(test_binary \"${name}_unit_test\${${name}_unit_tests_count}\")"
echo ""
echo "  add_executable(\${test_binary} EXCLUDE_FROM_ALL \"\${source_file}\")"
echo "  add_test([build]\${source_file}"
echo "    \${CMAKE_COMMAND} --build \${CMAKE_BINARY_DIR} --target \${test_binary})"
echo ""
echo "  add_test(NAME \${source_file} COMMAND \${test_binary})"
echo "  set_tests_properties(\${source_file} PROPERTIES DEPENDS [build]\${test_binary})"
echo "endfunction()"
echo ""
for src in $(find test -type f -name '*.cpp' | sed -e 's/^test\///')
do
  echo "add_unit_test($src)"
done
