#!/bin/sh

awk 'BEGIN {
  FS=" *= *"
}

/^ *$/ {
  next;
}

/^ *#.*$/ {
  next;
}

NF>1 {
  match($1, /^ */);
  $1=substr($1, RLENGTH+1);
  print "set "names[depth]"#"$1" "$2;
  next;
}

NF<=1 && match($0,/\[.*\]/) {
  name=substr($0, RSTART+1, RLENGTH-2);
  match($0, /^ */);
  depth=RLENGTH;
  names[depth]=names[depth-2]"#"name;
  print "append "names[depth-2]" "names[depth]
  next;
}

{
  print "Syntax error at line"NR;
  print "\""$0"\""
  exit 1;
}'
