#!/bin/sh

config__package__name=
config__package__bin=
{
  ppq_parse package__bin
  [ -z "$config__package__name" ] && ppq_parse package__name
} < package.ppq

ppq_build --target "${config__package__name}-bin" && build/"$config__package__bin"
